### ISSUE TITLE
[docs]: Example of event payload

### ISSUE THREAD

**Issue by bennypowers** [mathze/workflow-dispatch-action#24]
**Is your feature request related to a problem? Please describe.**
The README mentions that it's possible to send a workflow_dispatch event payload via the `payload` param, but it's not clear what format that param should take.

**Describe the solution you'd like**
Docs should provide an example of a given workflow, (e.g. the one demonstrated in https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) and the associated `payload` param.

e.g. should that look like:

```yml
  - name: "Start and wait for a workflow"
    id: startAndWaitWorkflow
    uses: mathze/workflow-dispatch-action@v1.1.0
    with:
      workflow-name: my-workflow.yml
      payload: |
        {
          "inputs": {
            "logLevel": "info",
            "tags": true,
            "environment": "dev"
          }
        }
```

**Describe alternatives you've considered**
The alternative here is for users to either discover the proper schema by trial and error or read the action source code
