### ISSUE TITLE
run-status and run-conclusion are both null after waiting for the dispatched workflow

### ISSUE THREAD

**Issue by rybesh** [mathze/workflow-dispatch-action#26]
**Describe the bug**
`run-status` and `run-conclusion` are both `null` after waiting for the dispatched workflow. 

**To Reproduce**

Triggering workflow:
```
name: end-to-end tests
on: [push]
jobs:
  dispatch-and-wait:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Dispatching end-to-end tests against $GITHUB_REF_NAME"
    - name: "Dispatch workflow"
      id: dispatch
      uses: mathze/workflow-dispatch-action@v1
      with:
        owner: periodo
        repo: periodo-tests
        ref: master
        token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
        use-marker-step: true
        workflow-name: run-tests-on-branch.yml
        payload: |
          { "client_branch": "${{  github.ref_name }}" }
    - run: echo 'Workflow log at https://github.com/periodo/periodo-tests/actions/runs/${{ steps.dispatch.outputs.run-id }}'
    - name: "Wait for workflow completion"
      id: wait
      uses: mathze/workflow-dispatch-action@v1
      with:
        owner: periodo
        repo: periodo-tests
        ref: master
        token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
        run-id: ${{ steps.dispatch.outputs.run-id }}
        fail-on-error: true
    - name: "Check result"
      run: |
        if [[ "completed" != "${{ steps.wait.outputs.run-status }}" ]] ||
           [[ "failure" != "${{ steps.wait.outputs.run-conclusion }}" ]] ||
           [[ false -ne ${{ steps.wait.outputs.failed }} ]]; then
           echo "Run-Status should be <completed> but was <${{ steps.wait.outputs.run-status }}>"
           echo "Run-Conclusion should be <failure> but was <${{ steps.wait.outputs.run-conclusion }}>"
           echo "Failed should be <false> but was <${{ steps.wait.outputs.failed }}>"
           exit 1
        else
          echo "Checks passed"
        fi
```

Triggered workflow:

```
name: end-to-end tests on branch
on:
  workflow_dispatch:
    inputs:
      external_ref_id:
        description: 'Identifier to use for unique run detection'
        required: true
        type: string
      client_branch:
        description: 'Client branch'
        required: true
        default: 'master'
        type: string
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ chrome, firefox ]
    env:
      CLIENT_BRANCH: ${{ github.event.inputs.client_branch }}
      HOST: http://127.0.0.1:5002
      ORCID_PASSWORD: ${{ secrets.ORCID_PASSWORD }}
      ORCID_USER: ${{ secrets.ORCID_USER }}
    steps:
      - name: ${{ github.event.inputs.external_ref_id }}
        run: echo
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/setup-python@v3
        with:
          python-version: 3
      - run: make start_client
      - uses: DevExpress/testcafe-action@latest
        with:
          args: >-
            ${{ matrix.browser }}
            */index.js
            --hostname localhost
            --retry-test-pages
            --skip-js-errors
            --selector-timeout 60000
      - run: make -C periodo-client stop
```

**Expected behavior**

`run-status` should be `completed`.

Actual results:
```
Run-Status should be <completed> but was <>
Run-Conclusion should be <failure> but was <>
Failed should be <false> but was <false>
```

See https://github.com/periodo/periodo-client/runs/6678904178

**Data/Screenshots**

Triggering workflow log:
https://github.com/periodo/periodo-client/runs/6678904178

Triggered workflow log:
https://github.com/periodo/periodo-tests/actions/runs/2417828291

**System (please complete the following information):**
- Runner-OS: ubuntu-latest
- Action-Version: v1
