### ISSUE TITLE
Error: Array contains no element matching the predicate.

### ISSUE THREAD

**Issue by djthornton1212** [mathze/workflow-dispatch-action#7]
Hello @mathze I'm trying to use your actions, but keep running into an error after the job is triggered.

![image](https://user-images.githubusercontent.com/99346713/156262562-f463b214-0461-4948-8b49-e8b04c48d541.png)

Any thoughts on what I might be doing wrong?

It appears as though it finds the job but unexpectedly fails. Note that the workflow_dispatch does start and successfully run.

Here's my step:
```yaml
 - name: Docker Dispatch
        id: dispatch
        uses: mathze/workflow-dispatch-action@v1
        with:
          owner: company
          repo: github-actions
          token: ${{ steps.generator.outputs.token }}
          workflow-name: docker-deploy.yml
          ref: develop
          payload: ${{ steps.json.outputs.ARTIFACT_JSON }}
          trigger-interval: 10s
          use-marker-step: true
          fail-on-error: true
          wait-interval: 30s
```
