### ISSUE TITLE
unable to get workflow ID when using "ref"

### ISSUE THREAD

**Issue by cjdcordeiro** [mathze/workflow-dispatch-action#89]
**Describe the bug**
When dispatching a workflow on a specific branch, the action will not be able to retrieve the workflow ID:

```
Trying to detect workflow run id
  Got workflow runs
  0 runs left that matches actual workflow.
  Found 0 new runs
  Found 0 removed runs
  Current runs in scope: []
  No result, retry in 1s
  Run list up-to-date
  Current runs in scope: []
  No result, retry in 1s
```

I've tried with and without a marker, with the same outcome.

**To Reproduce**

This is my step:

```yaml 
        uses: mathze/workflow-dispatch-action@v1.2.0
        id: run-tests
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          workflow-name: tests.yaml
```

**Expected behavior**

The run-id of the workflow should be retrieved, as it is when using the default branch.

**System (please complete the following information):**
- Runner-OS: ubuntu-22.04
- Action-Version: v1.2.0
